web/router.ex
defmodule IAmCheap.Router do
  use IAmCheap.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IAmCheap do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/session/new", SessionController, :new
    post "/session/create", SessionController, :create
    delete "/session/delete", SessionController, :delete
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", IAmCheap do
  #   pipe_through :api
  # end
end

lib/i_am_cheap/endpoint.ex
defmodule IAmCheap.Endpoint do
  use Phoenix.Endpoint, otp_app: :i_am_cheap

  socket "/socket", IAmCheap.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :i_am_cheap, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_i_am_cheap_key",
    signing_salt: "EaQ8UPZy"

  plug IAmCheap.Router
end

lib/i_am_cheap/repo.ex
defmodule IAmCheap.Repo do
  use Ecto.Repo, otp_app: :i_am_cheap
end

web/models/account.ex
defmodule IAmCheap.Account do
  use IAmCheap.Web, :model

  schema "accounts" do

  end

  def changeset(struct, params \\ %{}) do

  end
end

web/models/user.ex
defmodule IAmCheap.User do
  use IAmCheap.Web, :model

  schema "users" do
    field :email, :string
    field :password, :string, virtual: true
    field :confirm_password, :string, virtual: true
    field :crypted_password, :string
    field :token, :string
    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :password, :confirm_password])
    |> validate_required([:email, :password, :confirm_password])
    |> validate_length(:password, min: 6)
    |> validate_passwords_equal
    |> hash_password
    |> unique_constraint(:email)
  end

  defp hash_password(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: password}} ->
        put_change(changeset, :crypted_password, Comeonin.Bcrypt.hashpwsalt(password))
      _ ->
        changeset
    end
  end

  defp validate_passwords_equal(changeset) do
    password = get_field(changeset, :password)
    password_confirm = get_field(changeset, :confirm_password)
    validate_passwords_equal(changeset, password, password_confirm)
  end

  defp validate_passwords_equal(changeset, password, password_confirmation) do
    cond do
      password == password_confirmation ->
        changeset
      password != password_confirmation ->
        add_error(changeset, :confirm_password, "did not match password")
    end
  end
end

web/controllers/login_controller.ex
defmodule IAmCheap.LoginController do
  use IAmCheap.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def create(conn, params) do
    
  end
end

web/controllers/page_controller.ex
defmodule IAmCheap.PageController do
  use IAmCheap.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/session_controller.ex
require IEx
defmodule IAmCheap.SessionController do
  use IAmCheap.Web, :controller

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{ "email" => email, "password" => password }}) do
    user = IAmCheap.User |> IAmCheap.Repo.get_by(email: email)
    case user do
      nil ->
        conn
        |> put_flash(:error, "Please check your credentials")
        |> render("new.html")
      _ ->
        case Comeonin.Bcrypt.checkpw(password, user.crypted_password) do
          true ->
            conn
            |> put_session(:current_user, user.id)
            |> put_flash(:info, "Logic successfull")
            |> redirect(to: user_path(conn, :index))
          false ->
            conn
            |> put_flash(:error, "Incorrect password")
            |> render("new.html")
        end
    end
  end

  def delete(conn, _) do
    conn
    |> delete_session(:current_user)
    |> put_flash(:info, "Logged out")
    |> redirect(to: user_path(conn, :index))
  end
end

web/controllers/user_controller.ex
defmodule IAmCheap.UserController do
  require Logger
  use IAmCheap.Web, :controller

  alias IAmCheap.User
  def index(conn, _params) do
    users = IAmCheap.Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def show(conn, %{"id" => id}) do
    user = IAmCheap.Repo.get(User, id)
    render(conn, "show.html", user: user)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = %User{} |> User.changeset(user_params)

    case Repo.insert(changeset) do
      {:ok, changeset} ->
        conn
        |> put_flash(:info, "User create")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get(User, id)
    case Repo.delete user do
      {:ok, struct}       ->
        conn
        |> put_flash(:info, "User deleted")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "index.html")
    end
  end
end

web/views/error_view.ex
defmodule IAmCheap.ErrorView do
  use IAmCheap.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule IAmCheap.LayoutView do
  use IAmCheap.Web, :view

  def current_user(conn) do
    id = Plug.Conn.get_session(conn, :current_user)
    if id, do: IAmCheap.Repo.get(IAmCheap.User, id).email
  end

  def logged_in?(conn) do
    !!current_user(conn)
  end
end

web/views/login_view.ex
defmodule IAmCheap.LoginView do
  use IAmCheap.Web, :view

  def csrf_token(conn) do
    Plug.Conn.get_session(conn, :csrf_token)
  end
end

web/views/page_view.ex
defmodule IAmCheap.PageView do
  use IAmCheap.Web, :view
end

web/views/session_view.ex
defmodule IAmCheap.SessionView do
  use IAmCheap.Web, :view

  def csrf_token(conn) do
    Plug.Conn.get_session(conn, :csrf_token)
  end
end

web/views/user_view.ex
defmodule IAmCheap.UserView do
  use IAmCheap.Web, :view

  def changeset_error_string(changeset) do
    Enum.map(changeset.errors, fn({key, value}) ->
      "#{Phoenix.Naming.humanize(key)} #{translate_error(value)}"
    end) |> Enum.join("\n")
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome to IAmCheap!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li>
              <%= if logged_in?(@conn) do %>
                <%= link "Sign Out", to: session_path(@conn, :delete), method: :delete %>
              <% else %>
                <%= link "Sign In", to: session_path(@conn, :new)%>
                Or
                <%= link "Register", to: user_path(@conn, :new)%>
              <% end %>
            </li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/login/index.html.eex
<form method="POST" action="/login">
  <input type="hidden" name="csrf_token" value="<%= csrf_token(@conn) %>">
  <label>Email: <input type="text" name="email"/></label><br />
  <label>Password: <input type="password" name="password"/></label><br />
  <input type="submit" name="Login" value="Login"/>
</form>

web/templates/session/new.html.eex
<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  Email: <%= text_input f, :email, placeholder: "Email" %><br />
  Password: <%= password_input f, :password, placeholder: "Password" %><br />
  <%= submit "Sign in" %>
<% end %>

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
      <p><%=changeset_error_string(@changeset) %></p>
    </div>
  <% end %>

  <div class="form-group">
    <label>
      Email: <%= text_input f, :email %>
    </label>
    <br />
    <label>
      Password: <%= text_input f, :password %>
    </label>
    <br />
    <label>
      Repeat Password: <%= text_input f, :confirm_password %>
    </label>
    <br />
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%=user.email%></td>
      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset, action: user_path(@conn, :create) %>

web/templates/user/show.html.eex
<h2>Show user</h2>

<ul>
  <li><%=@user.email%></li>
</ul>

<%= link "Edit", to: user_path(@conn, :edit, @user) %><br />
<%= link "Back", to: user_path(@conn, :index) %>